Name: Jack_Smith_example's assignment
Date/Time: 2023-03-30 02:05:31.943079

============================= test session starts =============================
platform win32 -- Python 3.10.5, pytest-7.1.3, pluggy-1.0.0 -- C:\Users\evan\AppData\Local\Programs\Python\Python310\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\evan\Desktop\Autograder\Autograder\To_Grade
collecting ... collected 2 items

test.py::test_module PASSED                                              [ 50%]
test.py::test_function FAILED                                            [100%]

================================== FAILURES ===================================
________________________________ test_function ________________________________

    def test_function():
    
      #test that function is present in module
>     assert hasattr(module, 'my_fun'), "No 'my_fun' function found"
E     AssertionError: No 'my_fun' function found
E     assert False
E      +  where False = hasattr(module, 'my_fun')

test.py:25: AssertionError
=========================== short test summary info ===========================
FAILED test.py::test_function - AssertionError: No 'my_fun' function found
========================= 1 failed, 1 passed in 0.14s =========================
